name: Godis Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from the repository
    - name: Check out the repository
      uses: actions/checkout@v4

    # Set up Go environment
    - name: Set up Go 1.x
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.0'

    # Install dependencies
    - name: Install dependencies
      run: go mod download

    # Build the project
    - name: Build the project
      run: go build ./...

    # Run tests and generate report
    - name: Run tests and save result
      id: test-results
      run: |
        mkdir -p test-reports
        go test ./... -v | tee test-reports/results.txt

    # Build the project
    - name: Build the project
      run: test-summary/action@v2
      if: always()

    # Upload test results for later inspection
    - name: Upload test report
      uses: actions/upload-artifact@v3
      with:
        name: test-report
        path: test-reports/results.txt

    # Upload Markdown summary for display in the GitHub Actions summary
    - name: Upload test summary to GitHub Actions summary
      run: |
        cat test-reports/summary.md
        echo "" >> $GITHUB_STEP_SUMMARY
        cat test-reports/summary.md >> $GITHUB_STEP_SUMMARY