name: Godis Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from the repository
    - name: Check out the repository
      uses: actions/checkout@v4

    # Set up Go environment
    - name: Set up Go 1.x
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.0'

    # Install dependencies
    - name: Install dependencies
      run: go mod download

    # Build the project
    - name: Build the project
      run: go build ./...

    # Run tests and generate JUnit report
    - name: Run tests and generate JUnit report
      run: |
        mkdir -p test-reports
        go test ./... -v 2>&1 | tee >(go-junit-report > test-reports/junit.xml)

    # Upload the test report as an artifact
    - name: Upload test report
      uses: actions/upload-artifact@v3
      with:
        name: junit-test-report
        path: test-reports/junit.xml

    # Parse JUnit results and create a test summary
    - name: Create test summary
      uses: dorny/test-summary@v2
      with:
        format: markdown
        test-files: test-reports/junit.xml